def throw_exception():
    try:
        pass
    except:
        return "Exception: Something went wrong"
